# Generated by Django 4.0.1 on 2022-02-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_task_coordination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_coordination',
            new_name='task_coordinate',
        ),
    ]
