# Generated by Django 4.0.1 on 2022-01-24 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_or_off', models.BooleanField(default=False)),
                ('task_title', models.CharField(max_length=50)),
                ('task_username', models.CharField(max_length=20)),
                ('task_stu_id', models.CharField(max_length=20)),
                ('task_phone', models.CharField(max_length=20)),
                ('task_institution', models.CharField(max_length=20)),
                ('task_province', models.CharField(max_length=20)),
                ('task_city', models.CharField(max_length=30)),
                ('task_form_id', models.CharField(max_length=10)),
                ('vjuid', models.CharField(max_length=20)),
                ('vjvd', models.CharField(max_length=50)),
                ('vt', models.CharField(max_length=20)),
                ('UUkey', models.CharField(max_length=50)),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
